name: safety_check
description: "A new Flutter project."

publish_to: "none"

version: 1.0.8+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_native_splash: ^2.4.2
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  crypto: ^3.0.6
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  device_info_plus: ^11.0.0
  #  device_information: ^0.0.4
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.3.1
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.1.0
  package_info_plus: ^8.1.0
  permission_handler: ^11.4.0
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  fluttertoast: ^8.2.12
  linked_scroll_controller: ^0.2.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.3
  mime: ^2.0.0
  path: ^1.9.0
  image: ^4.5.3
  path_provider: ^2.1.5
  flutter_keyboard_visibility: ^6.0.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/fonts/
    - assets/models/
    - assets/images/
    - .env
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
